//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordReferenceBot.Core.Test {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordReferenceBot.Core.Test.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///&lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;en,es&quot; &gt;
        ///&lt;head&gt;
        ///&lt;meta http-equiv=&quot;Content-type&quot; content=&quot;text/html;charset=UTF-8&quot;&gt;
        ///&lt;title&gt;beautiful - English-Spanish Dictionary - WordReference.com&lt;/title&gt;
        ///&lt;meta name=&quot;description&quot; content=&quot;beautiful - Translation to Spanish, pronunciation, and forum discussions&quot;&gt;
        ///&lt;meta http-equiv=&quot;Content-Language&quot; content=&quot;en,es&quot;&gt;
        ///&lt;link title=&quot;WR English-Spanish&quot; rel=&quot;search&quot; type=&quot;application/opensearchdescription+xml&quot; href=&quot;//www.wordreference.com/2012/OpenSearch.aspx?dict=enes&quot;&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string beautiful {
            get {
                return ResourceManager.GetString("beautiful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;value&quot;: &quot;beautiful&quot;,
        ///    &quot;translations&quot;: [
        ///        {
        ///            &quot;wordExpression&quot;: &quot;beautiful&quot;,
        ///            &quot;meanings&quot;: [
        ///                &quot;(delightful to look at)&quot;
        ///            ],
        ///            &quot;possibleTranslations&quot;: [
        ///                &quot;hermoso/a &quot;,
        ///                &quot;precioso/a &quot;,
        ///                &quot;bello/la &quot;
        ///            ]
        ///        },
        ///        {
        ///            &quot;wordExpression&quot;: &quot;beautiful&quot;,
        ///            &quot;meanings&quot;: [
        ///                &quot;(person: very attractive)&quot;
        ///            ],
        ///            &quot;poss [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string beautifultranslations {
            get {
                return ResourceManager.GetString("beautifultranslations", resourceCulture);
            }
        }
    }
}
